config/routes.rb
Rails.application.routes.draw do
   
  devise_for :users, :path => ' ', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users

  get 'products/index'
  
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'
  
  get 'static_pages/landing_page'
    
  post 'static_pages/thank_you'
  
  post 'payments/create'
  
  

  root 'static_pages#landing_page'

  resources :products do
    resources :comments
  end
  
  resources :payments, only: [:index, :show, :new, :create]
  
  resources :orders, only: [:index, :show, :new, :create]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  
  validates :body, presence: true
  validates :user, presence: true
  validates :product, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 load_and_authorize_resource
  
  def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.new(comment_params)
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @product, notice: 'Review was created successfully.'}
        format.json { render :show, status: :created, location: @product}
        format.js
      else
        format.html { redirect_to @product, alert: 'Review was not saved.'}
        format.json { render json: @comment.errors, status: :unprocessable_entity}
      end
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    product = @comment.product
    @comment.destroy
    redirect_to product
  end
  
private

  def comment_params
    params.require(:comment).permit(:user_id, :first_name, :body, :rating)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_all_comments.html.erb
<div class = "product-reviews">
  <% @product.comments.each do |comment| %>
    <div class = "row">
      <hr>
      <p><%=comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
      <p><div class = "rated" data-score="<%= comment.rating %>"></div></p>
      <p><%= comment.body %></p>
    </div>

  <% if signed_in? && current_user.admin? %>
  <%= link_to ('<span class = "glyphicon glyphicon-remove"<</span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?'} %>
  <% end %>
<% end %>
</div>

app/views/comments/_comment.html.erb
<div class = "row">
  <hr>
  <p>
    <%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
    <% if signed_in? && current_user.admin? %>
      <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>
  <div class="rated" data-score="<%= comment.rating %>"></div>
  <p><%= comment.body %></p>
</div>

app/views/comments/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review: </h4>
<%= form_for([@product, @product.comments.build], remote: true) do |f| %>
    <p>
      <div class = "rating"></div>
    </p>
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body, class: "form-area form-control", :placeholder => "Send us a comment and rating." %>
    </p>
    <p>
      <%= f.submit "Submit" %>
    </p>
  <% end %>
<% end %>

app/views/comments/create.js.erb
$("#new_comment").html("Thank you for your review!");
$('.product-reviews').prepend("<%= j render @comment %>");
ratings();