config/routes.rb
Rails.application.routes.draw do
   
  devise_for :users, :path => ' ', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users

  get 'products/index'
  
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'
  
  get 'static_pages/landing_page'
    
  post 'static_pages/thank_you'
  
  post 'payments/create'
  
  

  root 'static_pages#landing_page'

  resources :products do
    resources :comments
  end
  
  resources :payments, only: [:index, :show, :new, :create]
  
  resources :orders, only: [:index, :show, :new, :create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Amber Mulholland | Newapp</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="text/javascript"> 
    Stripe.setPublishableKey('pk_test_Wl19S7V1BqL6eE4HNT6VmOhb'); 
  </script>
  <meta name = "viewport" content = "width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
  <body>
    <!--Navigation Bar --> 
    
    <% if signed_in? && current_user.admin? %>
      <nav>
        <div class = "navbar navbar-header navbar-inverse navbar-fixed-top" role = "navigation">
          <div class = "container-fluid">
            <div class = "project">
              <a href= "#">Amber Mulholland</a>
            </div>
            <div class = "navbar-header" id="heading">
              <button type = "button" class = "navbar-toggle" data-toggle = "collapse" data-target = ".navbar-collapse">
                <span class = "sr-only"> Toggle Navigation</span>
                <span class = "icon-bar"></span>
                <span class = "icon-bar"></span>
                <span class = "icon-bar"></span>
              </button>

              <div class = "navbar-collapse navbar-header collapse">
                <ul class = "nav navbar-nav">
                  <li><%= link_to "Home", static_pages_landing_page_path %></li>
                  <li><%= link_to "About", static_pages_about_path %></li>
                  <li><%= link_to "Contact", static_pages_contact_path %></li>
                  <li><%= link_to "Products", products_path %></li>
                  <li><%= link_to "Users", users_path %></li>
                  <li><%= link_to "Orders", orders_path %></li>
                  <li>
                    <% if user_signed_in? %>
                      <li>
                      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                      </li>
                    <% else %>
                      <li>
                      <%= link_to('Login', new_user_session_path) %>
                      </li>
                    <% end %>
                  </li>
                  <li> 
                    <%= form_tag("/products", method: "get", id: "search_form") do %>
                      <%= text_field_tag(:q, value = nil, options = {:id => "search_bar"}) %>
                      <%= submit_tag("Search", id: "search_button") %>
                    <% end %>
                  </li> 
                  </br>
                </ul>
              </div>
            </div>
          </div>
        </div>  
       </nav> 

    <%else%>
      <nav>
        <div class = "navbar navbar-header navbar-inverse navbar-fixed-top" role = "navigation">
          <div class = "container-fluid">
            <div class = "project">
              <a href= "#">Amber Mulholland</a>
            </div>
            <div class = "navbar-header" id="heading">
              <button type = "button" class = "navbar-toggle" data-toggle = "collapse" data-target = ".navbar-collapse">
                <span class = "sr-only"> Toggle Navigation</span>
                <span class = "icon-bar"></span>
                <span class = "icon-bar"></span>
                <span class = "icon-bar"></span>
              </button>

              <div class = "navbar-collapse navbar-header collapse">
                <ul class = "nav navbar-nav">
                  <li><%= link_to "Home", static_pages_landing_page_path %></li>
                  <li><%= link_to "About", static_pages_about_path %></li>
                  <li><%= link_to "Contact", static_pages_contact_path %></li>
                  <li><%= link_to "Products", products_path %></li>
                  <li>
                    <% if user_signed_in? %>
                      <li>
                      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                      </li>
                    <% else %>
                      <li>
                      <%= link_to('Login', new_user_session_path) %>
                      </li>
                    <% end %>
                  </li>
                  <li> 
                    <%= form_tag("/products", method: "get", id: "search_form") do %>
                      <%= search_field_tag :search, params[:search], :id => "search_bar" %>
                      <%= submit_tag("Search", id: "search_button") %>
                    <% end %>
                  </li> 
                  </br>
                </ul>
              </div>
            </div>
          </div>
        </div>  
      </nav> 
    <%end%>
    <!--Sign-In/Out Notice--> 
    
  <div class="notice">   
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>  
  </body>    
</html>